kind: Service
apiVersion: v1
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
    tier: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: http
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
        tier: frontend
        track: production
    spec:
      containers:
        - name: helloworld
          image: "jonathanfane/helloworld"
          ports:
            - name: http
              containerPort: 8000
