apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        tier: frontend
        track: canary
    spec:
      containers:
        - name: helloworld
          image: "jonathanfane/helloworld"
          ports:
            - name: http
              containerPort: 8000